ДЕЛО СДЕЛАНО
made-ml-in-prod-2022/ArtemPushPop pull request #1
Opened 2022-05-08 19:29 UTC by ArtemPushPop

Архитектура приведена на рисунке ниже. В ней поставлены в соотетствие модули, в которых описаны функции и порядок вызовов функций другими функциями. ![поясенение к пул рекввесту drawio](https://user-images.githubusercontent.com/72671982/167312383-c522ab82-fe36-409a-b4a4-306a5ac1ae2e.png)
соответствие критериям:
0: 1
1: 1
2: 0
3: 3
4: не предикт а евал, но надеюсь не важно, 3
5: 2
6: 2 в компании с гидрой
7: 0
8: 0
9: 3
10 : 0
11 : 0
12 : 1
13: 3
Hydra: 3
Залогированы метрики: 1

2022-05-11 14:26 UTC, SVizor42 commented on ml_project/models/utils.py
> +            model_config.model_pkl_path
Наверное тут надо конкретизировать, что используется не совсем most recently trained model, т.к. тип модели берется из конфига (по дефолту LogReg). А обучить мы могли целый зоопарк моделей. И не факт, что последней в списке была именно лог регрессия.

2022-05-11 15:04 UTC, SVizor42 commented on ml_project/features/processing.py
> +            ("imputer", SimpleImputer(strategy="constant", fill_value="M")),
У тебя только один категориальный признак в датасете? Вижу, что заполняешь его константным значением

2022-05-11 15:06 UTC, SVizor42 commented on ml_project/features/processing.py
> +                dataset.select_dtypes(include=["int64", "float64"]).columns,
Что произойдет, если прилетит категориальный признак с целыми значениями?

2022-05-11 15:13 UTC, SVizor42 commented on ml_project/pipeline.py
> +    save_model(model, cfg.model)
Можно было бы сохранить не только модель, но и весь пайплайн целиком (вместе с препроцессингом данных)

2022-05-11 15:46 UTC, SVizor42 commented on ml_project/data/utils.py
> +    load_file(config.data_url, config.file_location)
Строчка уехала выше докстринга

2022-05-11 15:47 UTC, SVizor42 commented on ml_project/eval.py
> +    X = preprocess_pipeline(cfg.pipeline, ds, eval=True)
Для продакшен кода лучше использовать более информативные идентификаторы

2022-05-11 15:51 UTC, SVizor42 commented on ml_project/models/utils.py
> +def save_eval(model_config: DictConfig, ds):
`ds` type?

2022-05-11 16:00 UTC, SVizor42 requested changes
1. Добавь плиз метку `hw1`.
2. В след раз приводи более развернутую оценку в пул реквесте: пункт, что сделал и балл, в конце - сумму. Так просто удобнее смотреть.
3. Много папок, которые по факту не используются (docs, settings etc). Если не планируешь использовать, то лучше их и не добавлять.
4. Приведи пожалуйста EDA в порядок. Вижу, что есть прототип с трансформером, но самих статистик или графиков нет. Добавь хотя бы самые простые.
5. Докстринги в модулях как-то выборочно приведены.
6. Прогони еще раз flake или любой другой линтер: поправь форматирование местами и посмотри опечатки.
7. Не нужно логировать все на уровне debug, сюда нужно направлять отладочную информацию. Основные этапы обучения/инференса модели я бы советовал логировать на уровне info.

2022-05-13 21:58 UTC, ArtemPushPop commented on ml_project/models/utils.py
> +            model_config.model_pkl_path
```outputs
├── eval
│   └── GaussianNB
│       └── 2022-05-06
│           └── 13-36-01
└── train
    ├── GaussianNB
    │   └── 2022-05-06
    │       └── 13-27-24
    └── LogReg
        └── 2022-05-14
            └── 00-46-59
```
Модели сохраняются по таким путям, так что если мы в eval попросим обработать данные например при помощи GaussianNB, а директории outputs/train/GaussianNB не будет существовать, тогда выпадет ошибка. Иначе же возьмется самая поздняя из моделей в папке outputs/train/GaussianNB

2022-05-13 22:21 UTC, ArtemPushPop commented on ml_project/features/processing.py
> +                dataset.select_dtypes(include=["int64", "float64"]).columns,
Я думаю это уже проблемы датасета, потому что такие колонки нужно помечать categorical. Предобработка конечно довольно простая. У меня есть идеи как исправить это, но это займет слишком много времени.

2022-05-13 22:24 UTC, ArtemPushPop commented on ml_project/data/utils.py
> +    load_file(config.data_url, config.file_location)
поправил

2022-05-14 08:28 UTC, ArtemPushPop commented on ml_project/pipeline.py
> +    save_model(model, cfg.model)
Это логично, я наверное в следущий раз сделаю обучение и референс в пайплайне. В этом задании я сделал крайне не расширяемый препроцессинг.

2022-05-14 08:28 UTC, ArtemPushPop commented on ml_project/eval.py
> +    X = preprocess_pipeline(cfg.pipeline, ds, eval=True)
поправил

2022-05-14 08:28 UTC, ArtemPushPop commented on ml_project/models/utils.py
> +def save_eval(model_config: DictConfig, ds):
поправил

2022-05-14 20:13 UTC, SVizor42 commented on ml_project/features/processing.py
> +                dataset.select_dtypes(include=["int64", "float64"]).columns,
Для этого как раз можно использовать конфиг для фичей, чтобы сразу понимать, какие признаки являются категориальными, а какие числовыми.

2022-05-14 21:03 UTC, SVizor42 approved these changes
Хорошо. +1 балл за EDA. Логирование метрик - это про MLFlow.
Итого - 23 балла.

2022-05-29 09:36 UTC, closed without merging