Done homework 2.
made-ml-in-prod-2022/ArtemPushPop pull request #2
Opened 2022-05-29 10:18 UTC by ArtemPushPop

## Выполнил домашку по [примеру](https://github.com/Mikhail-M/ml_project_example/tree/docker)

### Основная часть

1) Обернул целиком пайплайн из предобработчика данных и модели, соединенных в Pipeline.
**3 балла**

2) Написал ендпоинт health.
**1 балл**

3) Не написал юнит тест для предикта
**0 баллов**

4) Написал скрипт, который будет делать запросы к сервису
**2 балла**

5) Написал dockerfile, проверил на сборку, протыкал его скриптом из пункта 4, закоммитил его. Команда для сборки лежит в readme под заголовком Building your own image.
 **4 балла**

6) опубликов образ в докер хабе, [ссылка](https://hub.docker.com/repository/docker/gotovtsev/ml_prod_2)
 **2 балла**

7) В ридми написаны корректные команды docker pull run для подъема контейнера, загруженного из докер хаба. Протыкивается скриптом, делающим запросы. 
 **1 балл**

8) проведите самооценку
**1 балл**

### Дополнительная часть:
1) Сервис загружает модель либо локально лежащую в docker image, либо скачивает ее из открытого для скачивания файла в google.disk. С радостью бы сделал на s3, но в последний раз когда с ним игрался, меня в нем заблокировали..... :astonished:. Путь для скачивания передается через переменные окружения (откуда скачивать и ссылка на скачивание) 
**2 доп балла**

2) Для оптимизации размера docker image, я:
     - Переместил наиболее часто меняющиеся слои в конец, для того чтобы не менялись sha предыдущих, менее изменяемых слоев. Это место отмечено комментарием.
	  ```
	  # frequently changing layers
	  COPY server.py server.py
	  COPY ./model_pickle/pipeline.pkl ./model_pickle/pipeline.pkl
	  COPY configs ./configs
	  ```
     -  Оптимизировал количество пакетов, находящихся в requirements.txt. Там находятся только те пакеты которые нужны для инференса онлайн при помощи fastapi. Те пакеты которые требовались при обучении не включены в данный requirements.txt.
   
   **может быть 2 балла??**

3) Не сделал валидацию входных данных.
**0 баллов**

2022-06-08 11:41 UTC, nickdndev requested changes

2022-06-08 11:41 UTC, nickdndev commented on online_inference/Dockerfile
> +FROM python:3.9
для оптимизации попробуйте поиграться с разными версиями образови сравнить размер

2022-06-12 19:12 UTC, ArtemPushPop commented on online_inference/Dockerfile
> +FROM python:3.9
у меня остались последние 4гб на убунте, мне такие эксперименты не по корману... Там одна версия питона весит по гигу

2022-06-20 08:07 UTC, nickdndev commented
score:17 ( 1 балл за оптимищацию)

2022-06-20 08:07 UTC, merged